apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:8MEQX7aBiIAoj2W5tp8mP1Axa8VuGjkgsmScT0WRlSFuHjH6GseimH7Z7zPQ7Zn99Nj9wTLaGhwAKRemMmk42ssohO9FtTpXoX5kU3+9Ftk5JVID3MKjQ5TFur+rCw==,iv:vMEfjucK44xH9751AB/GB7hdxUtpyRagLGZ9N7CmnJ4=,tag:F9lIvFKEqsXGVLvalm0+4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7ehljyxn35j6che9gmejda0ng4588ltezj64fywsfq5xqfv39jqddd73n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbGZDM013WnJHWXlRemxS
            OEl2NHJUWTA2NVQ4emdva1NEQTlVV05wT0Z3CjZEWDA4dGk3dDNOU1VrK2NFTWRu
            ZTRjSFhGNXo0TG9CeE1vSEZQMjZ0TDgKLS0tIG5ERTJsdkJYcWp3UEc5QVdVOWVa
            Y093WGt4RlBVQjhGcWphRWQzWG00R28KQXqvD0bZqj0tnadnqX/I4tckN1XXuuhw
            d8B2bgkyF3OvaOJlVvJzKly9eaRkoEY/F3M7+GZAH7UyNeX5smdheQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T01:50:53Z"
    mac: ENC[AES256_GCM,data:Pp7j/jviCn86s5jMZNvrp6zvguaDbqdDmzDdWHAykfs1nslnGc2fyXsiIgJ68zgF1/on85bg65TtZkKKvpE/7In1MuDofwD5sM+1DfwCFZ9N4hcD4eAaNmUyJ4II7WJl5RdlYVg8mvaibsCGZ8QklAkj9GkxakDNBMjWLC0JmyU=,iv:y3WWCTuE2qWGfkFmehyWO9TWljKZPzZ8Iif5bLialQc=,tag:VDY/8dkUpG76bdGKa2ZEdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
