apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:aPs24JgBprVvdkQDQT9n6/AwfpXcTczPTvP1kK3MGus=,iv:bgOFb0CUAlZV5q0DVGMZkvMtEmasMJHrcR9f1xl1YBE=,tag:xhJUZu4aQ1lU6HxnOjeATQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7ehljyxn35j6che9gmejda0ng4588ltezj64fywsfq5xqfv39jqddd73n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTlYxeGZSZ1RDeFQ0c1M2
            Zk1NMXZoeVlhUjVpTllNY2NlQS9zSjgrU1hJCnlRMEdvb2p3QlI2TmpGWGUxL0NR
            RmU3UDlHVmliNFQ3Zm5KTHBVbnc4YTgKLS0tIGNpT0N4dEF5elRhSWxrSXVTY2U4
            YWVONkwxWjZEZ3Jvd1dxN0RtQmVmbkEKoenh7DQs04AwtEJq+iDDaBu4EWndOAjg
            WIZse/ZD7nh1EKJ9e7GqL7RRdy7X3uiYoei1ww6xC2RNd//IhtVxKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T01:50:53Z"
    mac: ENC[AES256_GCM,data:8/ZvQLMoG4QpkBownra8xsXPD2pQ+b3DjAtXX2KdqfFxdDZBk0IFeyrxVrUOdoIaxANISAD4S31BRa6NWGkycC+mKYoXqJ+rAyW/K9RiYJmgVef5Lz1FRXsFrnzjhqCu606sZevdicnlx83+e0RkRu7WEVGKVpX2+M9mFbRs8Pw=,iv:ozcThACM4yETyXeB2kwjI2xxyCxuRNRKBnty4DBRSbs=,tag:mp+CEkRQn7obMWdyseXV9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
